import os
import google.generativeai as genai
from PIL import Image

# Configure the Gemini API key
# Ensure you have the GOOGLE_API_KEY environment variable set
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))

def image_generation_function(
    person_image_path: str,
    campus_background_path: str,
    output_image_path: str,
) -> None:
    """
    Uses Gemini AI to generate a realistic image of the person at the campus.
    Takes the person's photo and the campus background as inputs.
    """
    
    # Open the images using PIL
    person_image = Image.open(person_image_path)
    campus_image = Image.open(campus_background_path)

    # Initialize the Gemini model
    # Note: Ensure your API key has access to this specific model preview
    model = genai.GenerativeModel('gemini-3-pro-image-preview')

    # Construct the prompt
    prompt = (
        "Generate a photorealistic image combining these two inputs. "
        "Place the person from the first image into the scene of the second image (the campus). "
        "Ensure the lighting, shadows, and perspective match so it looks like the person is actually standing there. "
        "Do not alter the person's face or identity."
    )

    # Send the request to Gemini
    # The input list includes the text prompt and the two image objects
    response = model.generate_content([prompt, person_image, campus_image])

    # Check if the response contains an image part and save it
    # The structure of the response depends on the specific model version, 
    # but typically generated images are in parts.
    if response.parts:
        # Assuming the first part is the image or the response object has a direct way to access it
        # For image generation models, the output is often bytes or a PIL image wrapper
        try:
            # This logic handles standard Gemini image output handling
            # You may need to adjust based on the specific SDK version for image-out models
            generated_image = response.parts[0].image 
            generated_image.save(output_image_path)
        except AttributeError:
            # Fallback if the SDK returns raw data differently
            print("Error: Could not extract image from response. Check API response structure.")
            print(response.text) # Print text if it failed to generate image
    else:
        print("No content generated by Gemini.")